### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [57]:
import numpy as np

In [58]:
vector = np.random.rand(10)
print('1. Vector: ')
display(vector)
display('Vector size (shape): ', vector.shape)

1. Vector: 


array([3.77728207e-01, 1.80523913e-01, 2.72786138e-02, 7.86228899e-01,
       4.19822690e-01, 4.17585839e-01, 7.33222273e-05, 8.05594625e-01,
       7.47450692e-01, 5.11027723e-01])

'Vector size (shape): '

(10,)

In [59]:
matrix = np.array([[11,14,17],
                  [20,23,26],
                  [29,32,35]])
print('2.Matrix: ')
display(matrix)
display('Matrix size (shape): ', matrix.shape)

2.Matrix: 


array([[11, 14, 17],
       [20, 23, 26],
       [29, 32, 35]])

'Matrix size (shape): '

(3, 3)


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [60]:
print('1. Завдання: Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.')
print('Розв\'язок: ')
print(np.around(vector + 10, decimals=2))

1. Завдання: Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
Розв'язок: 
[10.38 10.18 10.03 10.79 10.42 10.42 10.   10.81 10.75 10.51]


In [61]:
print('2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.')
print('Розв\'язок: ')
print(matrix * 2)

2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
Розв'язок: 
[[22 28 34]
 [40 46 52]
 [58 64 70]]


In [62]:
vector_square = vector ** 2

print('3. Створіть новий вектор, який містить квадрат кожного vector без циклів.')
print('Розв\'язок: ')
print(vector_square)


3. Створіть новий вектор, який містить квадрат кожного vector без циклів.
Розв'язок: 
[1.42678599e-01 3.25888830e-02 7.44122772e-04 6.18155881e-01
 1.76251091e-01 1.74377933e-01 5.37614902e-09 6.48982700e-01
 5.58682537e-01 2.61149333e-01]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [63]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [64]:
result_matrix = np.dot(B, A)
print('1. Множення матриць `B` i `A` (`result_matrix`):')
print(result_matrix)

1. Множення матриць `B` i `A` (`result_matrix`):
[[0.7281 0.5202]
 [0.2034 0.2846]]


In [65]:
print('2. Множення матриці `result_matrix` на вектор `C`:')
print(np.dot(result_matrix, C))

2. Множення матриці `result_matrix` на вектор `C`:
[[0.5202]
 [0.2846]]


In [66]:
print('3. Множення матриць `result_matrix` i `D`:')
print(np.dot(result_matrix, D))

3. Множення матриць `result_matrix` i `D`:
[[0.5202 0.7281]
 [0.2846 0.2034]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [67]:
print('1. Транспонована `result_matrix`: ')
display(result_matrix.T)

1. Транспонована `result_matrix`: 


array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [68]:
# display(vector)

In [69]:
# Не помітила різниці між `vector` і транспонованим ветором `vector.T`
print('2. Траспонований вектор `vector` і його структура:')
display(vector.T, vector.T.shape)

2. Траспонований вектор `vector` і його структура:


array([3.77728207e-01, 1.80523913e-01, 2.72786138e-02, 7.86228899e-01,
       4.19822690e-01, 4.17585839e-01, 7.33222273e-05, 8.05594625e-01,
       7.47450692e-01, 5.11027723e-01])

(10,)

In [70]:
column_vector = np.expand_dims(vector, axis=1)
print('3. Використання numpy.expand_dims:')
display(column_vector, column_vector.shape)

# тепер видно, що структура змінилась не (10,), а (10,1)

3. Використання numpy.expand_dims:


array([[3.77728207e-01],
       [1.80523913e-01],
       [2.72786138e-02],
       [7.86228899e-01],
       [4.19822690e-01],
       [4.17585839e-01],
       [7.33222273e-05],
       [8.05594625e-01],
       [7.47450692e-01],
       [5.11027723e-01]])

(10, 1)

In [71]:
print('4. Транспонування `column_vector`:')
display(column_vector.T, column_vector.T.shape)

4. Транспонування `column_vector`:


array([[3.77728207e-01, 1.80523913e-01, 2.72786138e-02, 7.86228899e-01,
        4.19822690e-01, 4.17585839e-01, 7.33222273e-05, 8.05594625e-01,
        7.47450692e-01, 5.11027723e-01]])

(1, 10)